---
title: "12_Spatial_LDA_patient_4"
author: "Xinyue_Cui"
date: "2024-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r , packages}
library(rstan)
library(dplyr)
library(EBImage)
library(ggplot2)
library(spatstat)
library(randomcoloR)
library(SpatialExperiment)
library(sp)
library(tidyr)
library(tibble)
library(maptools)
library(spdep)
library(adespatial)
```
##spe
```{r}
load(file = here::here("Output","RData","02_TNBC_spe_LC.rds"))
spe
```
##ppp_list
```{r}
s_coor <- spatialCoords(spe) |>
  data.frame()

df <- bind_cols(
  sample_id = spe$sample_id, 
  cell_id = dimnames(assay(spe))[[2]], 
  cell_type = spe$mm,
  cell_size = spe$cellSize
  ) |>
  data.frame() |>
  cbind(s_coor) |>
  left_join(mean_cluster_prop, by = "cell_type") |>
  mutate(tumor_not = ifelse(cell_type == "Other", 1, 0))
```

```{r}
sample_names <- df$sample_id %>%
  unique() %>%
  as.list()

ppp_list <- list()

for (i in seq_along(sample_names)) {
  spe_temp <- spe[ ,spe$sample_id == sample_names[[i]]]
  centroidX <- spatialCoords(spe_temp)[, 1]
  centroidY <- spatialCoords(spe_temp)[, 2]

  # Ensure df_temp is not empty
    ppp_temp <- ppp(
      centroidX,
      centroidY,
      window = owin(
        c(0, max(centroidX)),  # Correct range for x
        c(0, max(centroidY))   # Correct range for y
        ),
      marks = factor(spe_temp$mm)
      
    )

    ppp_list[[i]] <- ppp_temp
  }

names(ppp_list) <- sample_names
```
## tiles
```{r}
set.seed(1234) 
ppp_4<-ppp_list[[4]]
ppp_12<-ppp_list[[11]]

clusters_4 <- kmeans(cbind(ppp_4$x, ppp_4$y), centers = 1000)
ppp_4$cluster <- as.factor(clusters_4$cluster)
# clusters_12
```

```{r}
spe_4 <- spe[, spe$sample_id == "Sample_04"]
spe_12 <- spe[, spe$sample_id == "Sample_12"]
cell_tile_4 <- data.frame(cell_id = dimnames(assay(spe_4))[[2]],
                        cell_type = spe_4$mm,
                        tile_align = ppp_4$cluster)
cell_tile_4   
```
## centroides of tiles
```{r}
# Extract cluster centroids
centroids_4 <- aggregate(cbind(ppp_4$x, ppp_4$y), by=list(ppp_4$cluster), FUN=mean)
centroids_ppp_4 <- ppp(x=centroids_4$V1, y=centroids_4$V2, window=ppp_4$window)

centroids_voronoi <- dirichlet(centroids_ppp_4)
plot(centroids_voronoi)
```

```{r}
tile_df_4  <- data.frame(tile = centroids_4$Group.1, x = centroids_4$V1, y = centroids_4$V2)
tile_df_4 
```

## cell id in each tile (document)
```{r}
library(dplyr)
library(purrr)
# Group cell_id by 'tile_align' 
cell_groups <- cell_tile_4 %>%
  group_by(tile_align) %>%
  summarize(cells = list(cell_id)) %>%
  ungroup()

# left Join the groups
tile_df_4 <- tile_df_4 %>%
  left_join(cell_groups, by = c("tile" = "tile_align"))
tile_df_4 
```

## cell_type freqency table
```{r}
library(dplyr)

cell_type_freq<- list()

for (i in 1:dim(tile_df_4)[1]) {
  cell_tile_sub <- cell_tile_4 %>% filter(tile_align == i)
  cell_type_freq[[i]] <- table(cell_tile_sub$cell_type)
}


tile_df_4 <- tile_df_4 %>%
  mutate(cell_type_count = cell_type_freq)
tile_df_4
```


```{r}
tile_df_4$cell_type_count[[1]]
```
## Create long data

```{r}
cell_type_df <- data.frame(
  mm = levels(TNBC$mm),
  cell_type_id = seq_along(levels(TNBC$mm))
) %>%
  rename("cell_type"="mm")

print(cell_type_df)
```

```{r}
tiles_long_4 <- lapply(as.list(tile_df_4$tile), function(tile) {
  words_vector <- names(tile_df_4$cell_type_count[[tile]])
  counts_vector <- tile_df_4$cell_type_count[[tile]]
  
  # dataframe where each word is repeated according to its count
  data <- data.frame(
    tile_id = rep(tile, times = sum(counts_vector)),
    cell_type = rep(words_vector, times = counts_vector),
    stringsAsFactors = FALSE  # To keep 'word' as character type
  )
  
  return(data)
}) %>%
  bind_rows()  # Combine all the individual dataframes into one

dim(tiles_long_4)
```

```{r}
tiles_long_4 <- tiles_long_4 %>%
  left_join(cell_type_df, by= "cell_type")
tiles_long_4
```

## topic center in result of LDA
In 08_TNBC_topic proportion, import the libraries, read the csv, run the left join to create mean_result.
```{r}
# from 08_TNBC_topic_Proportion
mean_result_4 <- mean_result[mean_result$sample_id == '4', ]
mean_result_12 <- mean_result[mean_result$sample_id == '12', ]

S4_info <- mean_result_4  %>%
  select(cell_id,centroidX, centroidY,topic_assign)
S4_info <- S4_info %>% left_join(cell_tile_4, by = "cell_id")
S4_info
```

```{r}
library(dplyr)

# Calculate the mean of centroidX and centroidY for each topic
topic_means_4 <- mean_result_4 %>%
  group_by(topic_assign) %>%
  summarize(
    mean_centroidX = mean(centroidX, na.rm = TRUE),
    mean_centroidY = mean(centroidY, na.rm = TRUE)
  ) %>%
  ungroup()
```

## Compute spatial proximity

```{r}
# topic_centers- use result from LDA 

# calculate inverse distance weighting from each tile (doc) to the topic
calculate_influence <- function(
    tile_x, 
    tile_y, 
    topic_means
    ) {
  
  distances <- sqrt((topic_means$mean_centroidX - tile_x)^2 + (topic_means$mean_centroidY - tile_y)^2)
  # avoid division by zero by adding a small constant to distances
  influences <- 1 / (distances + 1e-6)
  # normalize influences so they sum to 1 for each document
  normalized_influences <- influences / sum(influences)
  return(normalized_influences)
}

# apply calculate_influence to each document to create the spatial_influence matrix
spatial_influence_4 <- t(
  sapply(1:nrow(tile_df_4), 
         function(i) {
  calculate_influence(tile_df_4$x[i], tile_df_4$y[i], topic_means_4)
}
)
)

head(spatial_influence_4)
sum(spatial_influence_4[1,])
spatial_influence_4[1000,]
```

# Apply Spatial LDA for 4 chain for 1000 iterations (warmup = 500)
## Apply Spatial LDA on patient 4
```{r}
# we know the simulated data, so 
# # N = sum(unlist(lapply(word_counts, function(x){sum(x)})))
# N <- dim(tiles_long_4)[1]
# D <- length(unique(tiles_long_4$tile_id))
# types <- tiles_long_4$cell_type_id
# tiles <- tiles_long_4$tile_id
# K <- 5
```

```{r}
# tiles<-as.vector(tiles)
# tiles<-as.integer(tiles)
# type(tiles)
# is.vector(tiles)
# is.integer(tiles)

```

```{r}
# stan_data_4 <- list(
#   D = D,
#   V = length(unique(types)),
#   K = K,
#   N = N,
#   words = types,
#   docs = tiles,
#   spatial_influence = spatial_influence_4
# )
# 
# str(stan_data_4)
```

```{r}
# fit_4.4 <- stan(
#   file = "/Users/cuixinyue/Desktop/TNBC_analysis/R_notebooks/slda.stan", 
#   data = stan_data_4, 
#   iter = 4000, 
#   chains = 2
#   )
```

```{r save_slda}
# save(fit_4.4 , fit_4.4 , file = "/Users/cuixinyue/Desktop/TNBC_analysis/Output/RData/Spatial_LDA_results/slda_lda_tile_4000_chain2_patient4.RData")
```

