---
title: "12_Spatial_LDA"
author: "Xinyue_Cui"
date: "2024-03-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Library
```{r warning=FALSE, message=FALSE}
#library(phyloseq)
library(dplyr)
library(magrittr)
library(ggplot2)
library(stringr)
#library(genefilter) 
library(rstan)
library(randomcoloR)
library(SpatialExperiment)
#library(DESeq2)
# library(here)
```

```{r}
load(file = here::here("Output","RData","02_TNBC_spe_LC.rds"))
spe
```

# Load the spatial LDA result

```{r}
# N = sum(unlist(lapply(word_counts, function(x){sum(x)})))
N <- dim(tiles_long)[1]
D <- length(unique(tiles_long$tile_id))
types <- tiles_long$cell_type_id
tiles <- tiles_long$tile_id
K <- 5
```

```{r lda result, eval=FALSE}
load(file = "/Users/cuixinyue/Desktop/TNBC_analysis/R_notebooks/slda_lda_tile_1000.RData")
fit
result<- rstan::extract(
    fit,
    permuted = TRUE,
    inc_warmup = FALSE,
    include = TRUE
  )

apply(result$theta[,3,], 2, median)
dim(result$theta[,3,])
```

```{r}
slda_theta<- result$theta
slda_phi<- result$phi
dim(result$phi)
dim(result$theta)
```

# Diagnostics
## Plots for effective sample size and R_hat
```{r}
iterUse = 1000
# for theta
 Rhat_theta <- matrix(
    nrow = dim(slda_theta )[2],
    ncol = dim(slda_theta)[3]
  )
  
  ESS_bulk_theta <- matrix(
    nrow = dim(slda_theta)[2],
    ncol = dim(slda_theta)[3]
  )
  
  for(sam in 1:dim(slda_theta)[2]){
    for(top in 1:dim(slda_theta)[3]){
      sims_theta <- matrix(
        slda_theta[ ,sam , top],
        nrow = (iterUse),
        ncol = chain,
        byrow = FALSE
      )
      Rhat_theta[sam, top] <- rstan::Rhat(sims_theta)
      ESS_bulk_theta[sam, top] <- rstan::ess_bulk(sims_theta)
    }
    
  }

Rhat_theta <- as.vector(Rhat_theta)
ESS_bulk_theta <- as.vector(ESS_bulk_theta)


# For phi
  
  Rhat_phi <- matrix(
    nrow = dim(slda_phi)[2],
    ncol = dim(slda_phi)[3]
  )
  ESS_bulk_phi <- matrix(
    nrow = dim(slda_phi)[2],
    ncol = dim(slda_phi)[3]
  )
  
  
  for(top in 1:dim(slda_phi)[2]){
    for(fea in 1:dim(slda_phi)[3]){
      sims_phi <- matrix(
        slda_phi[ , top, fea],
        nrow = (iterUse),
        ncol = chain,
        byrow = FALSE)
      Rhat_phi[top, fea] <- rstan::Rhat(sims_phi)
      ESS_bulk_phi[top, fea] <- rstan::ess_bulk(sims_phi)
      
    }
    
  }
  
  Rhat_phi <- as.vector(Rhat_phi)
  ESS_bulk_phi <- as.vector(ESS_bulk_phi)
  

# combine the R_hat and ESS_bulk
Rhat <- c(Rhat_theta, Rhat_phi)
ESS_bulk <- c(ESS_bulk_theta, ESS_bulk_phi)

#plot for R_hat
# R hat ~ 1.05
  p_rhat <- ggplot2::ggplot(
    data.frame(Rhat = Rhat)
  ) +
    ggplot2::geom_histogram(
      aes(x = Rhat),
      fill = "lavender",
      colour = "black",
      bins = 100
    ) +
    ggplot2::theme(
      plot.title = element_text(hjust = 0.5)
    )  +
    ggplot2::theme_minimal(base_size = 20) +
    ggplot2::xlab("")
  
  
  
  
  # ESS bulk and ESS tail at least 100 per Markov Chain in order to be reliable and indicate that estimates of respective posterior quantiles are reliable
  
  p_ess_bulk <- ggplot2::ggplot(
    data.frame(ESS_bulk = ESS_bulk)
  ) +
    ggplot2::geom_histogram(
      aes(x = ESS_bulk),
      fill = "lavender",
      colour = "black",
      bins = 100
    ) +
    ggplot2::theme(
      plot.title = element_text(hjust = 0.5)
    )   +
    ggplot2::theme_minimal(
      base_size = 20
    ) +
    ggplot2::xlab("")

list(p_ess_bulk, p_rhat)
```

## model assessment with mean
```{r}
# model assessment with mean 
source(here::here("R_notebooks", "06_LDA_scripts", "06_modelAssessment_mean.R"))

p_model_assessment_mean <- modelAssessment_mean(dtm = dtm,
                res = result,
                warm_up_iter = NULL,
                iter = 1000,
                cellTypeIndexToPlot = c(1:16)
                )
p_model_assessment_mean
```

```{r}
dtm <- as.data.frame.matrix(table(spe$sample_id, spe$mm)) %>% as.matrix()
dtm <- as.matrix(table(spe$sample_id, spe$mm))
dim(dtm)
dim_names <- dimnames(dtm)
col_names <- colnames(dtm)
```

```{r}
result_sim <- array(dim=c(iterUse,tiles , 16))
# Perform the multiplication using a for loop for the dimensions
for (i in 1:iterUse) {
  for (j in 1:tiles) {
    for (k in 1:16) {
      # Multiply the corresponding elements and sum over the common dimension
      result_sim [i, j, k] <- sum(slda_theta[i, j, ] * slda_phi[i, , k])
    }
  }
}

# Check the structure of the created 'sim' array
dim(result_sim)
result_sim <- result_sim*length(colnames(spe_4))

```


```{r}
warm_up_iter = NULL
iter = 2000
cellTypeIndexToPlot = c(1:16)
value <- Var2 <- NULL
  
  # determine the iteration used in posterior sampling (subtract warm up iterations)
  if (is.null(warm_up_iter)) {
    iterUse = iter / 2
  } else {
    iterUse = iter - warm_up_iter
  }
  
  x <- dtm

    x_4_cellCount <- data.frame(
    Var1 = rep(
      "x_mean_obs",
      dim(x)[2]
    ),
    Var2 = colnames(x),
    count = x[4,]
  )
   x_4_cellCount <- x_4_cellCount[cellTypeIndexToPlot, ]
  # draws from posterior predictive distribution
  ### x_sim <- result$theta[1:iterUse, , ] # iteration * tissues * topics
  mean_all <- apply(result_sim[1, , ], 2, mean)
  for (i in 2:iterUse){
    mean_x_sim_i <- apply(
      result_sim[i, ,], 
      2,
      mean)
    mean_all <- rbind(mean_all, mean_x_sim_i)
  }
  
  rownames(mean_all) <- c(
    paste0(
      "x_mean_rep",
      seq(1, iterUse)
    )
  )
  
  colnames(mean_all) <- colnames(x)
  
  mean_all <- mean_all[, cellTypeIndexToPlot]
  mean_all_long <- reshape2::melt(mean_all)
  
  p_hist <- ggplot2::ggplot(
    data = mean_all_long
  ) +
    ggplot2::geom_histogram(
      aes(
        x = value,
        group = Var2
      ),
      color = "#0072B2",
      fill = "#0072B2",
      bins = 50) +
    ggplot2::xlab("mean")+
    
    ggplot2::facet_wrap(~Var2, nrow = 4, scales = "free_x") +
    
    ggplot2::geom_vline(
      data = x_4_cellCount,
      aes(xintercept = count),
      color = "#CC79A7"
    ) +
    ggplot2::theme_update(
      text = element_text(size = 8)
    )
  
p_hist 
```


